fix: float number color caused PIL exception
Fix the following error:
python .\PaddleDetection\tools\infer.py -c .\picodet_l_640_tt100k_lcnet.yml  --infer_img ../../now.jpg
W0823 16:33:52.048938 20084 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 11.6
W0823 16:33:52.056516 20084 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[08/23 16:33:52] ppdet.utils.checkpoint INFO: Finish loading model weights: model_final.pdparams
[08/23 16:33:52] ppdet.data.source.category WARNING: anno_file 'new_dataset/voc/label_list.txt' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[08/23 16:33:52] ppdet.data.source.category WARNING: metric_type: VOC, load default categories of VOC.
100%|█████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
Traceback (most recent call last):
  File "D:\BigHomework\2022-2023-3\client\ai\PaddleDetection\tools\infer.py", line 177, in <module>
    main()
  File "D:\BigHomework\2022-2023-3\client\ai\PaddleDetection\tools\infer.py", line 173, in main
    run(FLAGS, cfg)
  File "D:\BigHomework\2022-2023-3\client\ai\PaddleDetection\tools\infer.py", line 130, in run
    trainer.predict(
  File "D:\BigHomework\2022-2023-3\client\ai\PaddleDetection\ppdet\engine\trainer.py", line 666, in predict
    image = visualize_results(
  File "D:\BigHomework\2022-2023-3\client\ai\PaddleDetection\ppdet\utils\visualizer.py", line 44, in visualize_results
    image = draw_bbox(image, im_id, catid2name, bbox_res, threshold)
  File "D:\BigHomework\2022-2023-3\client\ai\PaddleDetection\ppdet\utils\visualizer.py", line 106, in draw_bbox
    draw.line(
  File "D:\venvs\pdpd\lib\site-packages\PIL\ImageDraw.py", line 157, in line
    ink = self._getink(fill)[0]
  File "D:\venvs\pdpd\lib\site-packages\PIL\ImageDraw.py", line 115, in _getink
    ink = self.draw.draw_ink(ink)
TypeError: 'numpy.float32' object cannot be interpreted as an integer